import z from "zod";

export const factionTraitSchema = z.object({
  symbol: z.enum(["BUREAUCRATIC", "SECRETIVE", "CAPITALISTIC", "INDUSTRIOUS", "PEACEFUL", "DISTRUSTFUL", "WELCOMING", "ANARCHIST", "CONFLICTED", "AUTHORITARIAN", "OLIGARCHICAL", "DYNASTIC", "DEMOCRACTIC", "DECENTRALIZED", "SMUGGLERS", "SCAVENGERS", "REBELLIOUS", "EXILES", "PIRATES", "RAIDERS", "CLAN", "GUILD", "DOMINION", "FRINGE", "FORSAKEN", "ISOLATED", "LOCALIZED", "ESTABLISHED", "NOTABLE", "DOMINANT", "INESCAPABLE", "INNOVATIVE", "BOLD", "VISIONARY", "CURIOUS", "DARING", "EXPLORATORY", "RESOURCEFUL", "FLEXIBLE", "COOPERATIVE", "UNITED", "STRATEGIC", "INTELLIGENT", "RESEARCH_FOCUSED", "COLLABORATIVE", "PROGRESSIVE", "MILITARISTIC", "TECHNOLOGICALLY_ADVANCED", "AGGRESSIVE", "IMPERIALISTIC", "TREASURE_HUNTERS", "DEXTEROUS", "UNPREDICTABLE", "BRUTAL", "FLEETING", "ADAPTABLE", "SELF_SUFFICIENT", "DEFENSIVE", "PROUD", "DIVERSE", "INDEPENDENT", "SELF_INTERESTED", "FRAGMENTED", "COMMERCIAL", "FREE_MARKETS", "ENTREPRENEURIAL"]),
  name: z.string(),
  description: z.string()
});

export type FactionTrait = z.infer<typeof factionTraitSchema>;
